### ISSUE TITLE
"Could not parse certificate list."

### ISSUE THREAD

**Issue by Velyks** [magne4000/quassel-webserver#225] opened 2017-01-23 15:26 UTC
Versions: -
Node - 7.4.0
quassel - 0.12.2
quassel-webserver - latest git

Get the following errors on both latest firefox and chrome when trying to connect to quassel-webserver. I'm currently using a self-signed cert.

ERROR Object { message: "Could not parse certificate list.", cause: Error, send: true, alert: Object, origin: "client", toString: require<.tls</</TLSSocket.prototype._init/this.ssl<.error/error.toString() }  libquassel.js:23050:13
ERROR Object { message: "Could not parse certificate list.", cause: Error, send: true, alert: Object, origin: "client", toString: require<.tls</</TLSSocket.prototype._init/this.ssl<.error/error.toString() }  angular-controller.js:1027:9

**Comment by Velyks** [comment] 2017-01-23 16:47
Looks like its caused when you run quasselcore with the default self-signed cert. I changed over to a letsencrypt cert and it fixed my issue.

**Comment by magne4000** [comment] 2017-01-23 18:04
As the self signed cert is outdated, this could be the cause of the problem.
I'm closing the issue.

**Closed by magne4000** 2017-01-23 18:04 UTC
