### ISSUE TITLE
TLS error: Could not decrypt record or bad MAC

### ISSUE THREAD

**Issue by TheMythPT** [magne4000/quassel-webserver#273] opened 2019-02-21 14:09 UTC
I"m having this issue when following the instructions on GitHub to setup reverse proxy and even using https://domain.tld:port.

**Brower**
Chromium Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Core**
quassel v0.14-pre (unknown revision)

**OS**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**NodeJS Version**
Tested with: 7.10.1, 10.15.1,  11.10.0

**Comment by ohnx** [comment] 2019-02-21 16:34
Have you updated to the latest version of quassel-webserver? I used to have this issue continuously on Chrome, but it was fixed after upgrading. I still encounter it sometimes, but I find that if I focus the window until all the buffers have been loaded and reload when the error occurs, I can eventually get things working.

**Comment by magne4000** [comment] 2019-02-28 09:07
Duplicate of https://github.com/magne4000/quassel-webserver/issues/160

**Closed by magne4000** 2019-02-28 09:07 UTC
